### ISSUE TITLE
Is it possible to amend the function to allow for faceting by a grouping variable?

### ISSUE THREAD

**Issue by ghobro** [HughParsonage/waterfalls#10]
Suppose I have a data frame `df` with the standard variables `df$values` and df$labels`. Then suppose there is another grouping variable df$group`. I would like to be able to use `waterfalls` on this and facet by `group`, i.e.
```waterfalls::waterfall(df) |> facet_wrap(~group)```

**Comment by HughParsonage** [comment]
Can you provide an example? The issue is that the data in the data frame is transformed to be plotted as a waterfall. For example does package {cowplot} do a similar job?

**Comment by ghobro** [comment]
I've put a very simple example below. It would be adding a functionality to just add `|> facet_wrap(~company)` or have a parameter in the function `waterfall`. Thus we would have two charts: one for company  A with revenue 500, costs -100 and profit 400; and another for B with revenue 600, costs -150 and profit 450.

{cowplot} could do this but it might be problematic in a scenario where there are many individual values in the grouping variable and I want to succinctly split by that value without having to create separate plots for each of them.

```
library(tidyverse)

waterfall_data <- tibble(
  company = c("A", "A", "B", "B"),
  labels = c("Revenue", "Costs", "Revenue", "Costs"),
  values = c(500, -100, 600, -150)
)

waterfalls::waterfall(values = waterfall_data$values,
                      labels = waterfall_data$labels,
                      calc_total = TRUE,
                      total_axis_text = "Profit")
```

**Comment by HughParsonage** [comment]
I suspect this is too involved to be put in the waterfalls function with sufficient generality. However, the following construction should allow you to produce facetted waterfall charts:

```r
library(data.table)
library(magrittr)
library(ggplot2)

waterfall_data <- CJ(
  company = c("A", "A", "B", "B"),
  values = c(100, -20, 10, 20, 110)
)
waterfall_data[, category := letters[1:.N], by = .(company)]

new_waterfall_data <- copy(waterfall_data)
non_val_cat_noms <- setdiff(names(new_waterfall_data), c("values", "category"))

new_waterfall_data[, cumsum_v := cumsum(values), by = c(non_val_cat_noms)]

new_waterfall_data %>%
  .[, ymin := shift(cumsum_v, fill = 0), by = c(non_val_cat_noms)] %>%
  .[, ymax := copy(cumsum_v)] %>% 
  .[, category := factor(category)] %>%
  ggplot(aes(x = category,
             xmin = as.integer(category) - 0.35, 
             xmax = as.integer(category) + 0.35,
             ymin = ymin, ymax = ymax)) +
  geom_rect() +
  facet_wrap(~company)
```
