### ISSUE TITLE
Adjust the font size of the text in X-axis

### ISSUE THREAD

**Issue by ghost** [HughParsonage/waterfalls#3]
I love the package a lot. However, I didn't find a way to adjust the size of the text in X axis? Am I missing something or will this be in the future version?

Thanks,

**Comment by HughParsonage** [comment]
Glad you're enjoying the package!

I think you're missing something: the plot produced can be worked on just like any ggplot2 object, so you can use ggplot2 methods to adjust things like the axis font size.

```r
waterfall(values = c(0.56, 0.04, -0.85, 1.15, -0.73),
          labels = letters[1:5],
          calc_total = TRUE)
```
![image](https://user-images.githubusercontent.com/8111628/37548065-8478ec5c-29c9-11e8-8f88-d213b3a3dcdd.png)

```r
waterfall(values = c(0.56, 0.04, -0.85, 1.15, -0.73),
          labels = letters[1:5],
          calc_total = TRUE,
          print_plot = FALSE) +
  theme(axis.text.x = element_text(size = 20))
```
![image](https://user-images.githubusercontent.com/8111628/37548077-95435324-29c9-11e8-9e30-b6c64a25de52.png)

Reopen if this doesn't solve your issue.

**Comment by ghost** [comment]
This is so great. I was not aware of this full compatibility with ggplot2. This is awesome. Thanks for making such a great package.
